using System.Collections.Generic;
using System.Globalization;

namespace PeakVoiceFix
{
    public static class L
    {
        private static string _lang = "中文";
        private static Dictionary<string, string> _current;

        private static readonly Dictionary<string, string> ZH = new Dictionary<string, string>
        {
            // === UI 标签 ===
            { "ui_title", "语音详细状态" },
            { "ui_debug_title", "语音修复调试控制台 (Alt+J) | EvCode:186" },
            { "btn_copy_all", "复制全部" },
            { "btn_export", "导出文件" },
            { "btn_clear", "清空" },
            { "btn_dump", "打印语音底层名单" },
            { "filter_all", "全部" },
            { "filter_local", "本机" },
            { "client_not_connected", "客户端未连接" },
            { "voice_player_list", "语音底层名单" },
            { "ghost_tag", "[幽灵]" },
            { "exported_to", "已导出" },
            { "export_failed", "失败" },
            { "copied", "已复制" },

            // === UI 状态显示 ===
            { "label_local", "本机" },
            { "label_sync", "同步:" },
            { "label_abnormal", "异常:" },
            { "warn_majority", "⚠ [警告] 多数玩家({0}人)在另一频道!" },
            { "virtual_player", "虚拟玩家1" },
            { "sos_snapshot", "[SOS快照]" },
            { "sos_majority", "多数派" },
            { "sos_person", "人" },
            { "sos_detected", "检测到 {0} 掉线" },
            { "sos_target", "目标" },
            { "sos_last", "上次" },
            { "unknown", "未知" },
            { "region_not_reported", "区服未上报" },
            { "cache_snapshot", "[缓存快照]" },
            { "seconds_ago", "秒前" },
            { "not_connected", "未连接" },
            { "history", "[历史]" },
            { "notification_disconnected", "连接断开" },
            { "manual_operation", "[系统] 手动操作..." },

            // === 状态标签 ===
            { "state_synced", "同步" },
            { "state_connecting", "连接中" },
            { "state_disconnected", "断开" },
            { "state_connected", "已连接" },
            { "state_mismatch", "错位" },
            { "state_abnormal", "跨区" },
            { "state_unknown", "未知" },

            // === ClientState 本地化 ===
            { "cs_initializing", "初始化中..." },
            { "cs_authenticating", "验证中..." },
            { "cs_authenticated", "已验证" },
            { "cs_joining", "加入中..." },
            { "cs_joined", "已连接" },
            { "cs_disconnecting", "断开中..." },
            { "cs_disconnected", "断开" },
            { "cs_connecting_game", "连接到游戏服务器中..." },
            { "cs_connecting_master", "连接到主服务器中..." },
            { "cs_connecting_name", "连接到名称服务器中..." },

            // === 详细面板 ===
            { "detail_connecting_local", "连接中..." },
            { "voice_offline", "离线模式（语音未启用）" },

            // === NetworkManager 日志 ===
            { "log_state_change", "状态变更" },
            { "log_host_ip_change", "房主连接服务器变动" },
            { "log_host_disconnected", "[Host] 房主意外断开，正在自动恢复..." },
            { "log_loop_blind", "[循环] 已失败{0}次，暂时切换为盲连..." },
            { "log_wrong_freq", "[异频] 当前:{0} 目标:{1} | 纠正({2}/2)" },
            { "log_compromise", "[妥协] 纠正失败，驻留当前IP: {0}" },
            { "log_reconnect_go", "[重连] {0} | 区服:{1}" },
            { "log_reconnect_timeout", "[重连] 等待断开完成超时，本轮放弃" },
            { "log_decision", "[决策] 目标变更" },
            { "log_majority", "多数派({0}人)" },
            { "log_host", "房主" },
            { "log_auto_blind", "自动(盲连)" },
            { "log_sos_send", "[SOS] 发送求救" },
            { "log_sos_target", "目标" },
            { "log_sos_local", "本机" },
            { "log_sos_manual", "手动断开 (Manual)" },
            { "log_sos_received", "收到 {0} SOS (目标:{1})" },
            { "log_alt_k_disconnect", "[系统] Alt+K 手动断开" },
            { "log_alt_k_reconnect", "[系统] Alt+K 强制重连" },
            { "log_cache_snapshot", "[缓存快照] 记录数" },

            // === BepInEx 配置 ===
            { "cfg_cat_ui", "UI设置" },
            { "cfg_cat_adv", "高级与调试" },
            { "cfg_ui_position", "选择UI面板显示在屏幕的哪一侧。" },
            { "cfg_show_pro", "是否在面板中显示具体的已连接语音服务器IP地址和调试信息。" },
            { "cfg_offset_x_r", "距离屏幕右边缘的水平距离。" },
            { "cfg_offset_y_r", "距离屏幕上边缘的垂直距离。" },
            { "cfg_offset_x_l", "距离屏幕左边缘的水平距离。" },
            { "cfg_offset_y_l", "距离屏幕上边缘的垂直距离。" },
            { "cfg_font_size", "面板文字的基础大小。" },
            { "cfg_host_symbol", "显示在房主名字前的特殊符号。" },
            { "cfg_timeout", "如果连接卡住，超过多少秒判定为断开。" },
            { "cfg_retry_interval", "每次自动重连之间的冷却时间。" },
            { "cfg_manual_reconnect", "允许按 Alt+K 强制断开或重连语音。" },
            { "cfgn_voice_recovery", "自动恢复语音状态" },
            { "cfg_voice_recovery", "自动恢复本机远端玩家失效的语音状态引用，保留静音和屏蔽选择。不依赖 CrossplayStutterFix；关闭后仍显示异常。" },
            { "line2_voice_state_missing", "语音状态异常·本机播放受阻" },
            { "line2_voice_state_recovered", "语音状态已恢复" },
            { "cfg_max_name_len", "显示名字的最大字符数。" },
            { "cfg_latency_offset", "Ping值显示的水平像素偏移。" },
            { "cfg_auto_hide", "在机场常驻显示简易UI。关闭后简易UI只在出现异常或有通知时才冒出来；非机场场景一律只在异常时显示。" },
            { "cfg_show_ping", "在简易模式下方显示本机延迟。" },
            { "cfg_hide_menu", "打开ESC菜单时隐藏UI。" },
            { "cfg_virtual_player", "添加一个假玩家用于测试UI布局。" },
            { "cfg_virtual_name", "假玩家的名字。" },
            { "cfg_language", "语言(重启游戏生效) | Language(Need restart)" },

            // === 配置选项名 ===
            { "cfgn_ui_position", "UI位置" },
            { "cfgn_toggle_key", "详细UI切换键" },
            { "cfgn_show_pro", "显示连接到的语音服务器IP和详细信息" },
            { "cfgn_offset_x_r", "右侧边距" },
            { "cfgn_offset_y_r", "顶部边距(右)" },
            { "cfgn_offset_x_l", "左侧边距" },
            { "cfgn_offset_y_l", "顶部边距(左)" },
            { "cfgn_font_size", "字体大小" },
            { "cfgn_host_symbol", "房主标记符号" },
            { "cfgn_timeout", "重连超时时间 (s)" },
            { "cfgn_retry_interval", "重试间隔 (s)" },
            { "cfgn_manual_reconnect", "启用手动重置 (Alt+K)" },
            { "cfgn_max_name_len", "最大名字长度" },
            { "cfgn_latency_offset", "延迟对齐偏移量" },
            { "cfgn_auto_hide", "机场常驻简易UI" },
            { "cfgn_show_ping", "简易模式显示Ping" },
            { "cfgn_hide_menu", "ESC菜单界面时隐藏" },
            { "cfgn_virtual_player", "启用虚拟玩家" },
            { "cfgn_virtual_name", "虚拟玩家名字" },

            // === 区服控制 ===
            { "cfgn_forced_region", "强制区服-重启生效" },
            { "cfg_forced_region", "强制游戏连接到指定 Photon 区服。auto = 由游戏自己测速选择。\n⚠ 注意：强制区服不等于更快。没有加速器时，地理上更近的区往往路由更差——实测国内裸连强制 hk 可到 400ms+，而自动选区(eu) 只有 220ms 左右。请先用 Alt+J 控制台的「测各区延迟」看实际数据再决定。\n只影响你自己开房和主菜单连接；加入别人的房时游戏会自动切到房主所在区服，这是游戏本身的行为。可选 auto / asia / au / eu / hk / jp / sa / us / ussc / usw。改完需重启游戏。" },
            { "region_worse", "[区服] 强制 {0} 实测 {1}ms，而自动选区({2}) 只有 {3}ms —— 强制反而更慢，建议改回 auto。" },
            { "region_high", "[区服] 强制 {0} 实测 {1}ms，延迟偏高。没有加速器时强制区服通常不会更快。" },
            { "region_ping_partial", "已测到的部分结果:" },
            { "region_timeout", "[区服] 已强制 {0}，但 20 秒仍未连上主服务器。检查加速器，或把「强制区服」改回 auto。" },
            { "region_status_title", "区服状态" },
            { "region_game", "游戏区服" },
            { "region_voice", "语音区服" },
            { "region_room_code", "房间码" },
            { "region_from_code", "房间码解出" },
            { "region_forced", "强制设置" },
            { "region_auto", "auto（自动测速）" },
            { "region_cache_pun", "游戏测速缓存" },
            { "region_cache_voice", "语音测速缓存" },
            { "region_unlisted", "未知" },
            { "region_ping_title", "各区延迟" },
            { "region_ping_started", "[区服] 开始测速，约需 3-10 秒…" },
            { "region_ping_busy", "[区服] 正在测速中，请稍候。" },
            { "region_ping_failed", "[区服] 测速客户端连接失败。" },
            { "region_ping_nosettings", "[区服] 读不到 PhotonServerSettings，无法测速。" },
            { "region_ping_timeout", "[区服] 测速超时（30 秒）。" },
            { "region_ping_error", "[区服] 测速出错: {0}" },
            { "region_ping_empty", " 没有拿到任何区服，可能是网络不通。" },
            { "region_ping_hint", " ★ = Photon 判定的最佳区；— = 未测到；>3s = 不可达" },
            { "btn_region_ping", "测各区延迟" },
            { "btn_region_status", "区服状态" },
            { "mod_outdated", "{0}" },
            { "majority_region", "多数派语音区服: {0} ({1}，{2}人)" },
            { "cfg_toggle_key_v2", "切换语音面板的按键，循环顺序：关闭 → 简易 → 详细。" },

            // === 1.5.0 面板 ===
            { "hdr_room_region", "房间区服:" },
            { "hdr_room_voice", "房间语音服:" },
            { "hdr_local_state", "房间/语音地区:" },
            { "hdr_room_status", "房间情况:" },
            { "hdr_local_ping", "本机延迟:" },
            { "col_status", "[状态]" },
            { "col_name", "玩家名" },
            { "col_ping", "房间 - 语音" },
            { "line2_voice_server", "连接的语音服:" },
            { "line2_cannot_judge", "未知：本机断开语音服且对方未安装本模组 1.2 以上版本" },
            { "line2_not_in_voice", "未连入语音服" },
            { "src_local_guess", "本机推定" },
            { "src_host", "房主" },
            { "src_single", "1人上报" },
            { "rv_unknown", "未知（无人上报）" },
            { "local_isolated", "本机孤立" },
            { "voice_only_local", "语音房内只有本机" },
            { "err_voice_connect", "语音服连接错误" },
            { "snap_decision", "决策:" },
            { "snap_retry", "重连:" },
            { "snap_retry_fmt", "{0} 次 | 失败 {1} | IP不符 {2}" },
            { "snap_voiceroom", "语音房:" },
            { "snap_voiceroom_fmt", "{0} 人在线 | 判定 {1}/{2} | 幽灵 {3}" },
            { "snap_roomcode", "房间码:" },
            { "snap_voicename", "语音房名:" },
            { "room_name_mismatch", "语音房名与游戏房名 + _voice_ 不一致，请检查语音连接。" },
            { "room_name_pending", "房名信息缺失，暂时无法确认是否匹配。" },
            { "snap_forced", "强制区服:" },
            { "snap_no_decision", "尚未介入（语音正常，无需决策）" },
            { "snap_blind", "盲连" },
            { "newjoin", "新加入" },
            { "newjoin_connecting", "正在连接…" },
            { "newjoin_failed", "连接失败" },

            // === 诊断日志（只在状态变化时记一次，不广播给队友）===
            { "diag_vregion_change", "[诊断] 本机语音区服: {0} → {1}" },
            { "diag_vroom_change", "[诊断] 本机语音房: {0} → {1}" },
            { "diag_isolated", "[诊断] 本机孤立：语音房内只有自己，游戏房有 {0} 人" },
            { "diag_isolated_clear", "[诊断] 孤立解除，语音房内已有 {0} 人" },
            { "diag_roomvoice", "[诊断] 房间语音服判定为 {0}（来源: {1}）" },
            { "diag_roomvoice_lost", "[诊断] 房间语音服失去可信来源，转为未知" },
            { "diag_cross", "[诊断] {0} 跨区: 语音在 {1}，房间在 {2}" },
            { "diag_cross_clear", "[诊断] {0} 已回到房间区服 {1}" },
            { "diag_newjoin_ok", "[诊断] {0} 入房后 {1} 秒接入语音" },
            { "diag_newjoin_fail", "[诊断] {0} 入房 {1} 秒仍未接入语音" },
            { "diag_mode_change", "[诊断] 面板模式: {0} → {1}" },
            { "diag_cfg_change", "[诊断] 配置变更: {0} = {1}" },
            { "mode_off", "关闭" },
            { "mode_simple", "简易" },
            { "mode_detail", "详细" },

            // === 房间码兜底 ===
            { "cfgn_unknown_region", "未收录区服按此解析" },
            { "cfg_unknown_region", "游戏那张区服编码表漏收了 hk（香港），导致港服房的房间码首字符是 '-'，而本体解码时会把它夹成表里第一项 us（美国）——结果客机被送去美国区找一个在香港的房间，必然失败。这里指定 '-' 应该解析成哪个区。留空 = 不猜（保持本体行为，房间码进不去港服房）。与 BetterRoomShare 的同类修复兼容：结果已经正确时本 mod 不会再插手。" },
            { "cfgn_wait_master", "切区服后等主服务器就绪" },
            { "cfg_wait_master", "本体切换区服时是「断开 → 连接新区 → 立刻加房」，此时还没连上主服务器，加房必然失败（本体自己写了等待协程却没接上）。开启后会先等连上再加房，最多等 20 秒。" },
            { "joinwait_timeout", "[房间码] 等待主服务器超时（状态: {0}，区服: {1}），加房已取消。" },
            { "joinwait_ready", "[房间码] 主服务器已就绪（区服 {0}），继续加房" },

            // === 邀请握手兜底 ===
            { "cfgn_invite_retry", "邀请握手超时重试" },
            { "cfg_invite_retry", "接受 Steam 邀请后，客机要向大厅索要房间号，而房主只在自己确实待在房间里时才回应。本体这个握手没有超时、不重发、也不弹任何提示，房主当时在菜单/加载中/刚掉线，你就会永久静默卡在主菜单。开启后每 8 秒重试一次、最多 4 次，全部失败会明确告知原因。" },
            { "invite_requested", "[邀请] 已向大厅索要房间号（第 {0} 次）" },
            { "invite_retry", "[邀请] 8 秒未收到房间号，重新索要（{0}/{1}）" },
            { "invite_failed", "[邀请] 重试 {0} 次仍未收到房间号。房主可能不在房间里（在菜单、加载中或已掉线），也可能你连不上房主所在区服。让房主先进入房间再邀请，或改用房间码。" },
        };

        private static readonly Dictionary<string, string> EN = new Dictionary<string, string>
        {
            // === UI Labels ===
            { "ui_title", "Voice Detail Status" },
            { "ui_debug_title", "Voice Fix Debug Console (Alt+J) | EvCode:186" },
            { "btn_copy_all", "Copy All" },
            { "btn_export", "Export" },
            { "btn_clear", "Clear" },
            { "btn_dump", "Dump Photon Player List" },
            { "filter_all", "All" },
            { "filter_local", "Local" },
            { "client_not_connected", "Client not connected" },
            { "voice_player_list", "Photon Player List" },
            { "ghost_tag", "[Ghost]" },
            { "exported_to", "Exported to" },
            { "export_failed", "Failed" },
            { "copied", "Copied" },

            // === UI Status ===
            { "label_local", "Local" },
            { "label_sync", "Sync:" },
            { "label_abnormal", "Abnormal:" },
            { "warn_majority", "⚠ [WARN] Majority ({0}) on another channel!" },
            { "virtual_player", "Virtual Player 1" },
            { "sos_snapshot", "[SOS Snapshot]" },
            { "sos_majority", "Majority" },
            { "sos_person", "" },
            { "sos_detected", "Detected {0} disconnected" },
            { "sos_target", "Target" },
            { "sos_last", "Last" },
            { "unknown", "Unknown" },
            { "region_not_reported", "Region not reported" },
            { "cache_snapshot", "[Cache Snapshot]" },
            { "seconds_ago", "sec ago" },
            { "not_connected", "Not Connected" },
            { "history", "[History]" },
            { "notification_disconnected", "Disconnected" },
            { "manual_operation", "[System] Manual operation..." },

            // === Status Tags ===
            { "state_synced", "Synced" },
            { "state_connecting", "Connecting" },
            { "state_disconnected", "Disconnected" },
            { "state_connected", "Connected" },
            { "state_mismatch", "Mismatched" },
            { "state_abnormal", "Cross-region" },
            { "state_unknown", "Unknown" },

            // === ClientState Localized ===
            { "cs_initializing", "Initializing..." },
            { "cs_authenticating", "Authenticating..." },
            { "cs_authenticated", "Authenticated" },
            { "cs_joining", "Joining..." },
            { "cs_joined", "Joined" },
            { "cs_disconnecting", "Disconnecting..." },
            { "cs_disconnected", "Disconnected" },
            { "cs_connecting_game", "Connecting to game server..." },
            { "cs_connecting_master", "Connecting to master server..." },
            { "cs_connecting_name", "Connecting to name server..." },

            // === Detail Panel ===
            { "detail_connecting_local", "Connecting..." },
            { "voice_offline", "Offline mode (voice disabled)" },

            // === NetworkManager Logs ===
            { "log_state_change", "State change" },
            { "log_host_ip_change", "Host server connection change" },
            { "log_host_disconnected", "[Host] Unexpected disconnect, recovering..." },
            { "log_loop_blind", "[Loop] Failed {0} times, switching to blind..." },
            { "log_wrong_freq", "[WrongIP] Current:{0} Target:{1} | Fix({2}/2)" },
            { "log_compromise", "[Compromise] Fix failed, staying on: {0}" },
            { "log_reconnect_go", "[Reconnect] {0} | Region:{1}" },
            { "log_reconnect_timeout", "[Reconnect] Timed out waiting for disconnect, skipping this round" },
            { "log_decision", "[Decision] Target changed" },
            { "log_majority", "Majority ({0})" },
            { "log_host", "Host" },
            { "log_auto_blind", "Auto (Blind)" },
            { "log_sos_send", "[SOS] Sending SOS" },
            { "log_sos_target", "Target" },
            { "log_sos_local", "Local" },
            { "log_sos_manual", "Manual Disconnect" },
            { "log_sos_received", "Received {0} SOS (Target:{1})" },
            { "log_alt_k_disconnect", "[System] Alt+K Manual disconnect" },
            { "log_alt_k_reconnect", "[System] Alt+K Force reconnect" },
            { "log_cache_snapshot", "[Cache Snapshot] Count" },

            // === BepInEx Config Descriptions ===
            { "cfg_cat_ui", "UI Settings" },
            { "cfg_cat_adv", "Advanced & Debug" },
            { "cfg_ui_position", "Which side of the screen to display the UI panel." },
            { "cfg_show_pro", "Show connected voice server IP and debug info in the panel." },
            { "cfg_offset_x_r", "Horizontal offset from right edge." },
            { "cfg_offset_y_r", "Vertical offset from top edge." },
            { "cfg_offset_x_l", "Horizontal offset from left edge." },
            { "cfg_offset_y_l", "Vertical offset from top edge." },
            { "cfg_font_size", "Base font size of the panel." },
            { "cfg_host_symbol", "Symbol displayed before host's name." },
            { "cfg_timeout", "Seconds before connection is deemed disconnected." },
            { "cfg_retry_interval", "Cooldown between auto-reconnect attempts." },
            { "cfg_manual_reconnect", "Allow Alt+K to force disconnect/reconnect voice." },
            { "cfgn_voice_recovery", "Auto Recover Voice State" },
            { "cfg_voice_recovery", "Restore invalid remote-player voice state references locally, preserving mute and block choices. CrossplayStutterFix is not required. Detection remains active when disabled." },
            { "line2_voice_state_missing", "Voice state error · local playback blocked" },
            { "line2_voice_state_recovered", "Voice state restored" },
            { "cfg_max_name_len", "Max display characters for names." },
            { "cfg_latency_offset", "Horizontal pixel offset for ping display." },
            { "cfg_auto_hide", "Keep the simple overlay visible while in the airport. When off, it only appears on a problem or a notification. Outside the airport it always only appears on a problem." },
            { "cfg_show_ping", "Show local ping below simple mode UI." },
            { "cfg_hide_menu", "Hide UI when ESC menu is open." },
            { "cfg_virtual_player", "Add a fake player for UI layout testing." },
            { "cfg_virtual_name", "Name of the fake player." },
            { "cfg_language", "语言(重启游戏生效) | Language(Need restart)" },

            // === Config Option Names ===
            { "cfgn_ui_position", "UI Position" },
            { "cfgn_toggle_key", "Toggle Key" },
            { "cfgn_show_pro", "Show Server IP & Details" },
            { "cfgn_offset_x_r", "Right Margin" },
            { "cfgn_offset_y_r", "Top Margin (Right)" },
            { "cfgn_offset_x_l", "Left Margin" },
            { "cfgn_offset_y_l", "Top Margin (Left)" },
            { "cfgn_font_size", "Font Size" },
            { "cfgn_host_symbol", "Host Symbol" },
            { "cfgn_timeout", "Reconnect Timeout (s)" },
            { "cfgn_retry_interval", "Retry Interval (s)" },
            { "cfgn_manual_reconnect", "Enable Manual Reset (Alt+K)" },
            { "cfgn_max_name_len", "Max Name Length" },
            { "cfgn_latency_offset", "Latency Alignment Offset" },
            { "cfgn_auto_hide", "Persistent Simple UI in Airport" },
            { "cfgn_show_ping", "Show Ping in Simple Mode" },
            { "cfgn_hide_menu", "Hide on ESC Menu" },
            { "cfgn_virtual_player", "Enable Virtual Player" },
            { "cfgn_virtual_name", "Virtual Player Name" },

            // === Region control ===
            { "cfgn_forced_region", "Forced Region - needs restart" },
            { "cfg_forced_region", "Force the game to connect to a specific Photon region. auto = let the game pick by ping.\nWARNING: forcing a region does not mean lower latency. Without a proxy/VPN, a geographically closer region often has worse routing - measured from mainland China, forcing hk can hit 400ms+ while auto (eu) sits around 220ms. Use \"Ping Regions\" in the Alt+J console before deciding.\nOnly affects hosting your own room and the main-menu connection; joining someone else's room follows the host's region, which is the game's own behaviour. Accepts auto / asia / au / eu / hk / jp / sa / us / ussc / usw. Restart required." },
            { "region_worse", "[Region] Forced {0} measures {1}ms, but auto ({2}) was only {3}ms - forcing made it worse. Consider setting it back to auto." },
            { "region_high", "[Region] Forced {0} measures {1}ms, which is high. Without a proxy, forcing a region usually does not help." },
            { "region_ping_partial", "Partial results measured so far:" },
            { "region_timeout", "[Region] Forced {0}, but still not connected to a master server after 20s. Check your connection, or set Forced Region back to auto." },
            { "region_status_title", "Region Status" },
            { "region_game", "Game region" },
            { "region_voice", "Voice region" },
            { "region_room_code", "Room code" },
            { "region_from_code", "decoded" },
            { "region_forced", "Forced setting" },
            { "region_auto", "auto (ping-based)" },
            { "region_cache_pun", "Game ping cache" },
            { "region_cache_voice", "Voice ping cache" },
            { "region_unlisted", "Unknown" },
            { "region_ping_title", "Region Latency" },
            { "region_ping_started", "[Region] Pinging regions, takes 3-10s..." },
            { "region_ping_busy", "[Region] A ping run is already in progress." },
            { "region_ping_failed", "[Region] Ping client failed to connect." },
            { "region_ping_nosettings", "[Region] PhotonServerSettings unavailable, cannot ping." },
            { "region_ping_timeout", "[Region] Ping run timed out (30s)." },
            { "region_ping_error", "[Region] Ping error: {0}" },
            { "region_ping_empty", " No regions returned - network may be unreachable." },
            { "region_ping_hint", " * = Photon's best region; - = not measured; >3s = unreachable" },
            { "btn_region_ping", "Ping Regions" },
            { "btn_region_status", "Region Status" },
            { "mod_outdated", "{0}" },
            { "majority_region", "Majority voice region: {0} ({1}, {2} people)" },
            { "cfg_toggle_key_v2", "Key that cycles the voice panel: off -> simple -> detailed." },

            // === 1.5.0 panel ===
            { "hdr_room_region", "Room region:" },
            { "hdr_room_voice", "Room voice server:" },
            { "hdr_local_state", "Local game/voice:" },
            { "hdr_room_status", "Room:" },
            { "hdr_local_ping", "Local ping:" },
            { "col_status", "[Status]" },
            { "col_name", "Player" },
            { "col_ping", "room - voice" },
            { "line2_voice_server", "voice server:" },
            { "line2_cannot_judge", "Unknown: local voice is disconnected and this player has no BetterPeakVoiceFix 1.2+" },
            { "line2_not_in_voice", "not in the voice room" },
            { "src_local_guess", "local guess" },
            { "src_host", "host" },
            { "src_single", "1 report" },
            { "rv_unknown", "unknown (nobody reported)" },
            { "local_isolated", "local isolated" },
            { "voice_only_local", "only this client in the voice room" },
            { "err_voice_connect", "wrong voice server" },
            { "snap_decision", "Decision:" },
            { "snap_retry", "Retries:" },
            { "snap_retry_fmt", "{0} | failed {1} | wrong IP {2}" },
            { "snap_voiceroom", "Voice room:" },
            { "snap_voiceroom_fmt", "{0} online | classified {1}/{2} | ghosts {3}" },
            { "snap_roomcode", "Room code:" },
            { "snap_voicename", "Voice room name:" },
            { "room_name_mismatch", "Voice room name does not equal the game room name + _voice_. Check the voice connection." },
            { "room_name_pending", "Room name information is missing; matching cannot be confirmed yet." },
            { "snap_forced", "Forced region:" },
            { "snap_no_decision", "not engaged (voice is fine, nothing to decide)" },
            { "snap_blind", "blind connect" },
            { "newjoin", "Joined" },
            { "newjoin_connecting", "connecting..." },
            { "newjoin_failed", "connection failed" },

            // === Diagnostics (logged once per change, never broadcast) ===
            { "diag_vregion_change", "[Diag] Local voice region: {0} -> {1}" },
            { "diag_vroom_change", "[Diag] Local voice room: {0} -> {1}" },
            { "diag_isolated", "[Diag] Local isolated: alone in the voice room while {0} players are in the game room" },
            { "diag_isolated_clear", "[Diag] Isolation cleared, {0} clients in the voice room" },
            { "diag_roomvoice", "[Diag] Room voice server resolved to {0} (source: {1})" },
            { "diag_roomvoice_lost", "[Diag] Room voice server lost every trusted source, now unknown" },
            { "diag_cross", "[Diag] {0} is cross-region: voice on {1}, room on {2}" },
            { "diag_cross_clear", "[Diag] {0} returned to the room region {1}" },
            { "diag_newjoin_ok", "[Diag] {0} reached voice {1}s after joining" },
            { "diag_newjoin_fail", "[Diag] {0} still not in voice {1}s after joining" },
            { "diag_mode_change", "[Diag] Panel mode: {0} -> {1}" },
            { "diag_cfg_change", "[Diag] Config changed: {0} = {1}" },
            { "mode_off", "off" },
            { "mode_simple", "simple" },
            { "mode_detail", "detailed" },

            // === Room code fallback ===
            { "cfgn_unknown_region", "Unlisted region resolves to" },
            { "cfg_unknown_region", "The game's region-code table is missing hk (Hong Kong), so a Hong Kong room's code starts with '-' and the game's decoder clamps that to the first table entry, us. The result is that the client is sent to the US region to look for a room that lives in Hong Kong, which always fails. This setting decides what '-' should resolve to. Leave empty to not guess (vanilla behaviour). Compatible with BetterRoomShare's equivalent fix: if the result is already correct, this mod stays out of it." },
            { "cfgn_wait_master", "Wait for master server after region swap" },
            { "cfg_wait_master", "When the game switches region it does disconnect -> connect to new region -> join room immediately, while still connecting to the master server, so the join always fails (the game has a wait coroutine for this but never calls it). With this on, the join waits for the master server first, up to 20 seconds." },
            { "joinwait_timeout", "[RoomCode] Timed out waiting for the master server (state: {0}, region: {1}); join cancelled." },
            { "joinwait_ready", "[RoomCode] Master server ready (region {0}), continuing to join" },

            // === Invite handshake fallback ===
            { "cfgn_invite_retry", "Retry the invite handshake on timeout" },
            { "cfg_invite_retry", "After accepting a Steam invite the client asks the lobby for the room ID, and the host only answers while actually sitting in a room. The game's handshake has no timeout, never retries and shows nothing at all, so if the host is in a menu, still loading or has just dropped, you stay silently stuck on the main menu forever. With this on the request is retried every 8 seconds, up to 4 times, and the failure message names both likely causes." },
            { "invite_requested", "[Invite] Asked the lobby for the room ID (attempt {0})" },
            { "invite_retry", "[Invite] No room ID after 8s, asking again ({0}/{1})" },
            { "invite_failed", "[Invite] Still no room ID after {0} attempts. The host may not be in a room (in a menu, loading, or just dropped), or you may not be able to reach the host's region. Ask the host to enter the room before inviting you, or use the room code instead." },
        };

        public static string DetectDefault()
        {
            var culture = CultureInfo.CurrentUICulture;
            return culture.Name.StartsWith("zh") ? "中文" : "English";
        }

        public static void Init(string lang)
        {
            _lang = lang;
            _current = (_lang == "中文") ? ZH : EN;
        }

        /// <summary>供区服名等"仅中文才附译名"的场合使用。</summary>
        public static bool IsChinese => _lang == "中文";

        public static string Get(string key)
        {
            if (_current != null && _current.TryGetValue(key, out var v)) return v;
            if (ZH.TryGetValue(key, out var fallback)) return fallback;
            return key;
        }

        public static string Get(string key, params object[] args)
        {
            return string.Format(Get(key), args);
        }
    }
}
